### PR TITLE
Use server-based default ACL 

### PR DESCRIPTION
**Pull request by b123400**
connect https://github.com/SkygearIO/skygear-server/issues/309

### CODE REVIEW

**Comment by oursky-travis** [comment]
@b123400, thanks for your PR! By analyzing the history of the files in this pull request, we identified @ben181231, @cheungpat and @limouren to be potential reviewers.

**Comment by cheungpat** [comment]
@b123400 I just want to let you know that the PR needs changes because of lint check errors.

**Comment by b123400** [comment]
This is interesting, I didn't edit any swift file and swiftlint's failing

**Comment by cheungpat** [comment]
> This is interesting, I didn't edit any swift file and swiftlint's failing

If this happens, this is usually caused by updated swiftlint version which might have additional checks for swift code. To verify that this happened. Trigger a rebuild on the master branch at travis and then make additional pull request to fix the lint errors. Then rebase this pull request.

**Comment by cheungpat** [comment]
@b123400 Would be great if you could fix the lint on the master branch first.

**Comment by b123400** [comment]
OK, I guess it will take some time

**Comment by cheungpat** [comment]
I will merge this pull request after skygeario/skygear-server#329 is merged.

**Pull request merged**
