### PR TITLE
Supply `deviceID` in `[SKYDatabase-saveSubscription:completionHandler:]`

### PR DESCRIPTION
**Pull request by limouren**
connects #23

### CODE REVIEW

**Comment by cheungpat** [comment]
The same problem applies to fetch and delete operations, would you be kind enough to fix those too?

**Comment by limouren** [comment]
Argh, missed those. No problem.

**Comment by limouren** [comment]
@cheungpat PR updated with fixes of fetch and delete operations.

**Comment by cheungpat** [comment]
@limouren thank you for your pull request

**Comment by limouren** [comment]
You are welcome 🎉 🎉 🎉

**Pull request merged**
