### PR TITLE
New signup login, remove SKYUser object

### PR DESCRIPTION
**Pull request by Steven-Chan**
connect #112

### CODE REVIEW

**Comment by Steven-Chan** [comment]
@cheungpat ready for review

**Comment by Steven-Chan** [comment]
@cheungpat updated with the rename

**Comment by cheungpat** [comment]
@Steven-Chan please merge [this](https://github.com/SkygearIO/skygear-SDK-iOS/pull/116) and rebase

**Comment by Steven-Chan** [comment]
@cheungpat rebased

**Pull request merged**
